language: java
jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
before_install:
  - chmod +x mvnw
script:
  - mvn clean package install -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
    - $HOME/.m2