language: java

jdk: oraclejdk8

install: true

addons:
  sonarcloud:
    organization: caiomelo8-github

# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
before_install:
  - chmod +x mvnw
script:
  - mvn clean jacoco:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'